/*
 * Copyright 2017-2020 Samuel Rowe
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Sunday, November 26, 2017

#ifndef COM_ONECUBE_ZEN_COMPILER_COMPILER_AST_NODE_TYPE_H
#define COM_ONECUBE_ZEN_COMPILER_COMPILER_AST_NODE_TYPE_H

#include <com/onecube/zen/Configuration.h>

/*******************************************************************************
 * ASTNodeType                                                                 *
 *******************************************************************************/

/**
 * @class ASTNodeType
 * @ingroup zen_compiler_ast
 * @author Samuel Rowe
 * @since zen 1.0
 */
enum zen_ASTNodeType_t {

    ZEN_AST_NODE_TYPE_UNKNOWN,

    ZEN_AST_NODE_TYPE_TERMINAL,

    ZEN_AST_NODE_TYPE_COMPILATION_UNIT,

    ZEN_AST_NODE_TYPE_IMPORT_DECLARATION,

    ZEN_AST_NODE_TYPE_ANNOTATED_COMPONENT_DECLARATION,

    ZEN_AST_NODE_TYPE_ANNOTATIONS,

    ZEN_AST_NODE_TYPE_ANNOTATION,

    ZEN_AST_NODE_TYPE_ANNOTATION_TYPE,

    ZEN_AST_NODE_TYPE_ANNOTATION_ATTRIBUTE,

    ZEN_AST_NODE_TYPE_COMPONENT_DECLARATION,

    ZEN_AST_NODE_TYPE_FUNCTION_DECLARATION,

    ZEN_AST_NODE_TYPE_FUNCTION_PARAMETERS,

    ZEN_AST_NODE_TYPE_FUNCTION_BODY,

    ZEN_AST_NODE_TYPE_STATEMENT_SUITE,

    ZEN_AST_NODE_TYPE_SIMPLE_STATEMENT,

    ZEN_AST_NODE_TYPE_STATEMENT,

    ZEN_AST_NODE_TYPE_EMPTY_STATEMENT,

    ZEN_AST_NODE_TYPE_VARIABLE_DECLARATION,

    ZEN_AST_NODE_TYPE_VARIABLE_DECLARATOR,

    ZEN_AST_NODE_TYPE_CONSTANT_DECLARATION,

    ZEN_AST_NODE_TYPE_CONSTANT_DECLARATOR,

    ZEN_AST_NODE_TYPE_ASSERT_STATEMENT,

    ZEN_AST_NODE_TYPE_BREAK_STATEMENT,

    ZEN_AST_NODE_TYPE_CONTINUE_STATEMENT,

    ZEN_AST_NODE_TYPE_RETURN_STATEMENT,

    ZEN_AST_NODE_TYPE_THROW_STATEMENT,

    ZEN_AST_NODE_TYPE_COMPOUND_STATEMENT,

    ZEN_AST_NODE_TYPE_IF_STATEMENT,

    ZEN_AST_NODE_TYPE_IF_CLAUSE,

    ZEN_AST_NODE_TYPE_ELSE_IF_CLAUSE,

    ZEN_AST_NODE_TYPE_ELSE_CLAUSE,

    ZEN_AST_NODE_TYPE_ITERATIVE_STATEMENT,

    ZEN_AST_NODE_TYPE_LABEL_CLAUSE,

    ZEN_AST_NODE_TYPE_WHILE_STATEMENT,

    ZEN_AST_NODE_TYPE_FOR_STATEMENT,

    ZEN_AST_NODE_TYPE_FOR_PARAMETER,

    ZEN_AST_NODE_TYPE_TRY_STATEMENT,

    ZEN_AST_NODE_TYPE_TRY_CLAUSE,

    ZEN_AST_NODE_TYPE_CATCH_CLAUSE,

    ZEN_AST_NODE_TYPE_CATCH_FILTER,

    ZEN_AST_NODE_TYPE_TYPE_NAME,

    ZEN_AST_NODE_TYPE_FINALLY_CLAUSE,

    ZEN_AST_NODE_TYPE_SYNCHRONIZE_STATEMENT,

    ZEN_AST_NODE_TYPE_WITH_STATEMENT,

    ZEN_AST_NODE_TYPE_WITH_PARAMETERS,

    ZEN_AST_NODE_TYPE_WITH_PARAMETER,

    ZEN_AST_NODE_TYPE_CLASS_DECLARATION,

    ZEN_AST_NODE_TYPE_EXTENDS_CLAUSE,

    ZEN_AST_NODE_TYPE_CLASS_SUITE,

    ZEN_AST_NODE_TYPE_CLASS_MEMBER,

    // AST_NODE_TYPE_CONSTRUCTOR_DECLARATION,

    // ZEN_AST_NODE_TYPE_ENUMERATION_DECLARATION,

    // ZEN_AST_NODE_TYPE_ENUMERATION_BASE_CLAUSE,

    // ZEN_AST_NODE_TYPE_ENUMERATION_SUITE,

    // ZEN_AST_NODE_TYPE_ENUMERATE,

    ZEN_AST_NODE_TYPE_EXPRESSIONS,

    ZEN_AST_NODE_TYPE_EXPRESSION,

    ZEN_AST_NODE_TYPE_ASSIGNMENT_EXPRESSION,

    ZEN_AST_NODE_TYPE_CONDITIONAL_EXPRESSION,

    ZEN_AST_NODE_TYPE_LOGICAL_OR_EXPRESSION,

    ZEN_AST_NODE_TYPE_LOGICAL_AND_EXPRESSION,

    ZEN_AST_NODE_TYPE_INCLUSIVE_OR_EXPRESSION,

    ZEN_AST_NODE_TYPE_EXCLUSIVE_OR_EXPRESSION,

    ZEN_AST_NODE_TYPE_AND_EXPRESSION,

    ZEN_AST_NODE_TYPE_EQUALITY_EXPRESSION,

    ZEN_AST_NODE_TYPE_RELATIONAL_EXPRESSION,

    ZEN_AST_NODE_TYPE_SHIFT_EXPRESSION,

    ZEN_AST_NODE_TYPE_ADDITIVE_EXPRESSION,

    ZEN_AST_NODE_TYPE_MULTIPLICATIVE_EXPRESSION,

    ZEN_AST_NODE_TYPE_UNARY_EXPRESSION,

    ZEN_AST_NODE_TYPE_POSTFIX_EXPRESSION,

    ZEN_AST_NODE_TYPE_SUBSCRIPT,

    ZEN_AST_NODE_TYPE_FUNCTION_ARGUMENTS,

    ZEN_AST_NODE_TYPE_MEMBER_ACCESS,

    ZEN_AST_NODE_TYPE_POSTFIX_OPERATOR,

    ZEN_AST_NODE_TYPE_PRIMARY_EXPRESSION,

    ZEN_AST_NODE_TYPE_MAP_EXPRESSION,

    ZEN_AST_NODE_TYPE_MAP_ENTRIES,

    ZEN_AST_NODE_TYPE_MAP_ENTRY,

    ZEN_AST_NODE_TYPE_LIST_EXPRESSION,

    ZEN_AST_NODE_TYPE_NEW_EXPRESSION
};

/**
 * @memberof ASTNodeType
 */
typedef enum zen_ASTNodeType_t zen_ASTNodeType_t;

#endif /* COM_ONECUBE_ZEN_COMPILER_COMPILER_AST_NODE_TYPE_H */