// Sunday, November 26, 2017

#ifndef COM_ONECUBE_ZEN_COMPILER_COMPILER_AST_NODE_TYPE_H
#define COM_ONECUBE_ZEN_COMPILER_COMPILER_AST_NODE_TYPE_H

#include <com/onecube/zen/Configuration.h>

/*******************************************************************************
 * ASTNodeType                                                                 *
 *******************************************************************************/

/**
 * @class ASTNodeType
 * @ingroup zen_compiler_ast
 * @author Samuel Rowe
 * @since zen 1.0
 */
enum zen_ASTNodeType_t {
    
    AST_NODE_TYPE_UNKNOWN,
    
    AST_NODE_TYPE_TERMINAL,

    AST_NODE_TYPE_COMPILATION_UNIT,
    
    AST_NODE_TYPE_IMPORT_DECLARATION,
    
    AST_NODE_TYPE_ANNOTATED_COMPONENT_DECLARATION,

    AST_NODE_TYPE_ANNOTATIONS,

    AST_NODE_TYPE_ANNOTATION,

    AST_NODE_TYPE_ANNOTATION_TYPE,

    AST_NODE_TYPE_ANNOTATION_ATTRIBUTE,

    AST_NODE_TYPE_COMPONENT_DECLARATION,

    AST_NODE_TYPE_FUNCTION_DECLARATION,

    AST_NODE_TYPE_FUNCTION_PARAMETERS,

    AST_NODE_TYPE_FUNCTION_BODY,

    AST_NODE_TYPE_STATEMENT_SUITE,

    AST_NODE_TYPE_SIMPLE_STATEMENT,

    AST_NODE_TYPE_STATEMENT,

    AST_NODE_TYPE_EMPTY_STATEMENT,

    AST_NODE_TYPE_VARIABLE_DECLARATION,

    AST_NODE_TYPE_VARIABLE_DECLARATOR,

    AST_NODE_TYPE_CONSTANT_DECLARATION,

    AST_NODE_TYPE_CONSTANT_DECLARATOR,

    AST_NODE_TYPE_ASSERT_STATEMENT,

    AST_NODE_TYPE_BREAK_STATEMENT,

    AST_NODE_TYPE_CONTINUE_STATEMENT,

    AST_NODE_TYPE_RETURN_STATEMENT,

    AST_NODE_TYPE_THROW_STATEMENT,

    AST_NODE_TYPE_COMPOUND_STATEMENT,

    AST_NODE_TYPE_IF_STATEMENT,

    AST_NODE_TYPE_IF_CLAUSE,

    AST_NODE_TYPE_ELSE_IF_CLAUSE,

    AST_NODE_TYPE_ELSE_CLAUSE,

    AST_NODE_TYPE_ITERATIVE_STATEMENT,

    AST_NODE_TYPE_LABEL_CLAUSE,

    AST_NODE_TYPE_WHILE_STATEMENT,

    AST_NODE_TYPE_FOR_STATEMENT,

    AST_NODE_TYPE_FOR_PARAMETERS,

    AST_NODE_TYPE_TRY_STATEMENT,

    AST_NODE_TYPE_TRY_CLAUSE,

    AST_NODE_TYPE_CATCH_CLAUSE,

    AST_NODE_TYPE_CATCH_FILTER,

    AST_NODE_TYPE_TYPE_NAME,

    AST_NODE_TYPE_FINALLY_CLAUSE,

    AST_NODE_TYPE_SYNCHRONIZE_STATEMENT,

    AST_NODE_TYPE_WITH_STATEMENT,

    AST_NODE_TYPE_CLASS_DECLARATION,

    AST_NODE_TYPE_EXTENDS_CLAUSE,

    AST_NODE_TYPE_CLASS_SUITE,

    AST_NODE_TYPE_CLASS_MEMBER,

    // AST_NODE_TYPE_CONSTRUCTOR_DECLARATION,

    AST_NODE_TYPE_ENUMERATION_DECLARATION,

    AST_NODE_TYPE_ENUMERATION_BASE_CLAUSE,

    AST_NODE_TYPE_ENUMERATION_SUITE,

    AST_NODE_TYPE_ENUMERATE,

    AST_NODE_TYPE_EXPRESSIONS,

    AST_NODE_TYPE_EXPRESSION,

    AST_NODE_TYPE_ASSIGNMENT_EXPRESSION,

    AST_NODE_TYPE_CONDITIONAL_EXPRESSION,

    AST_NODE_TYPE_LOGICAL_OR_EXPRESSION,

    AST_NODE_TYPE_LOGICAL_AND_EXPRESSION,

    AST_NODE_TYPE_INCLUSIVE_OR_EXPRESSION,

    AST_NODE_TYPE_EXCLUSIVE_OR_EXPRESSION,

    AST_NODE_TYPE_AND_EXPRESSION,

    AST_NODE_TYPE_EQUALITY_EXPRESSION,

    AST_NODE_TYPE_RELATIONAL_EXPRESSION,

    AST_NODE_TYPE_SHIFT_EXPRESSION,

    AST_NODE_TYPE_ADDITIVE_EXPRESSION,

    AST_NODE_TYPE_MULTIPLICATIVE_EXPRESSION,

    AST_NODE_TYPE_UNARY_EXPRESSION,

    AST_NODE_TYPE_POSTFIX_EXPRESSION,

    AST_NODE_TYPE_SUBSCRIPT,

    AST_NODE_TYPE_FUNCTION_ARGUMENTS,

    AST_NODE_TYPE_MEMBER_ACCESS,

    AST_NODE_TYPE_POSTFIX_OPERATOR,

    AST_NODE_TYPE_PRIMARY_EXPRESSION,

    AST_NODE_TYPE_MAP_EXPRESSION,

    AST_NODE_TYPE_MAP_ENTRIES,

    AST_NODE_TYPE_MAP_ENTRY,

    AST_NODE_TYPE_LIST_EXPRESSION,

    AST_NODE_TYPE_NEW_EXPRESSION
};

/**
 * @memberof ASTNodeType
 */
typedef enum zen_ASTNodeType_t zen_ASTNodeType_t;

#endif /* COM_ONECUBE_ZEN_COMPILER_COMPILER_AST_NODE_TYPE_H */