// Monday, March 19, 2018

#ifndef ZEN_BINARY_ENTITY_FORMAT_H
#define ZEN_BINARY_ENTITY_FORMAT_H

#include <com/onecube/zen/Configuration.h>

#define ZEN_BINARY_ENTITY_FORMAT_MAGIC_NUMBER 0xFEB72000
#define ZEN_BINARY_ENTITY_FORMAT_MAJOR_VERSION 1
#define ZEN_BINARY_ENTITY_FORMAT_MINOR_VERSION 0

#endif /* ZEN_BINARY_ENTITY_FORMAT_H */